name: _bike_services_use_cases_real_adapters
description: Bike services use cases real adapters

publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  either_dart: ^0.1.4
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.5.0

  _bike_services_use_cases:
    path: ../..
  _core:
    path: ../../../../shared/all/core

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  flutter_lints: ^1.0.0
